import type { Metadata } from "next";
import "@styles/reset.css";
import { Roboto } from "next/font/google";

const roboto = Roboto({
	weight: ["400", "900"],
	style: ["normal", "italic"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Hi, I'm Ayuu!!",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja" className={roboto.className}>
			<body>{children}</body>
		</html>
	);
}
