name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci ./src/**/*
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'latest'
      - name: Install dependencies
        run: pnpm install
      - name: Run Stylelint
        run: pnpm run check:stylelint
